version: "3.8"
services:
  # vue:
  #   image: node:16.13.0
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 80:3000
  #   container_name: frontend_ssafy_app
  #   networks:
  #     - frontend
  nginx:
    image: nginx:latest
    container_name: nginx    
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/jenkins/workspace/INVIEW/frontend/default.conf:/etc/nginx/conf.d/default.conf
      - /home/jenkins/workspace/INVIEW/frontend/dist:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt # 추가
    restart: always
    depends_on:
      - spring-boot

  db:
    image: mysql:5.7
    container_name: backend_db
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: inview
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: ssafy
      TZ: Asia/Seoul
    privileged: true
    volumes: #앞이 로컬 파일시스템 경로, 뒤쪽이 컨테이너 내부 경로
      - /home/jenkins/workspace/INVIEW/db/initdb.d:/docker-entrypoint-initdb.d 
      - /home/jenkins/workspace/INVIEW/db/conf.d:/etc/mysql/conf.d
      - /home/systemv/mysql/data:/var/lib/mysql
    networks:
      - backend

  kurento:
    container_name: backend_kurento
    image: kurento/kurento-media-server:latest
    restart: always
    ports:
       - "8888:8888"
      #  - "8888:8888/tcp"
      #  - "5000-5050:5000-5050/udp"
    environment: 
        TZ: "Asia/Seoul"
        KMS_STUN_IP: "172.26.1.220"
        KMS_STUN_PORT: "3478"
        KMS_TURN_URL: "myuser:mypassword@172.26.1.220:3478?transport=udp"
    networks: 
      - backend
    working_dir: /tmp # RUN, CMD, ADD, COPY등이 이루어질 기본 디렉토리를 설정합니다.
    volumes: # 컨테이너 외부에 파일시스템을 마운트 할 때 사용합니다. 반드시 지정하지 않아도 마운트 할 수 있지만, 기본적으로 지정하는 것이 좋습니다.
      - ./:/tmp

  spring-boot: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_ssafy_app
    restart: always
    ports: 
      - "8080:8080"        
      - "8443:8443"
    environment: 
      # SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/inview?&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
      # SPRING_DATASOURCE_USERNAME: root
      # SPRING_DATASOURCE_PASSWORD: ssafy
      # DATABASE_DRIVER: com.mysql.cj.jdbc.Driver
      JAVA_TOOL_OPTIONS: "-Dkms.url=ws://kurento:8888/kurento"
      server.address: 0.0.0.0
      TZ: Asia/Seoul
    depends_on:
      - db
      - kurento
      - coturn_server
    networks:
      - backend
      # - frontend

  coturn_server:
    image: instrumentisto/coturn:4.5.1
    restart: always
    network_mode: "host"
    volumes:
      - /etc/turnserver.conf:/etc/coturn/turnserver.conf
      - /etc/default/coturn:/etc/default/coturn
networks:
  backend: 
  # frontend:
        
